In [1]:
import sys
import pandas as pd
import openpyxl

print("Python:", sys.executable)
print("pandas:", pd.__version__)
print("openpyxl:", openpyxl.__version__)

C:\Users\User\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

Python: C:\Users\User\anaconda3\python.exe
pandas: 2.3.3
openpyxl: 3.1.5

In [2]:
from pathlib import Path

# Wir sind im Notebook-Ordner: notebooks/student_housing/
path_xlsx = Path("../../data/raw/student_housing/Studentenwohnheime_DE.xlsx")

print("Exists:", path_xlsx.exists())
print("Path:", path_xlsx.resolve())

Exists: True
Path: C:\Users\User\Desktop\DATA INFORMATION SCIENCE\DIS08\dis08-miete-nrw\data\raw\student_housing\Studentenwohnheime_DE.xlsx

In [3]:
xls = pd.ExcelFile(path_xlsx)
xls.sheet_names

['StaGus\xa0-\xa0Auswertung']

In [4]:
sheet = xls.sheet_names[0]
df_raw = pd.read_excel(path_xlsx, sheet_name=sheet, header=None)
df_raw.shape

C:\Users\User\anaconda3\lib\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

(256, 54)

In [5]:
df_raw.head(15)

,0,1,2,3,4,5,6,7,8,9,...,44,45,46,47,48,49,50,51,52,53
0,Tab.2.5.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Studierendenwohnheime, Wohnheimplätze, Studier...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Studierendenwohnheime,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Studierenden-wohnheime,NaN,Studierende,NaN,NaN
5,NaN,2001,NaN,2002,NaN,2003,NaN,2004,NaN,2005,...,NaN,2023,NaN,2024,NaN,2025,NaN,WS 2024/2025,2025,2024
6,NaN,Anzahl,Plätze 3),Anzahl,Plätze 3),Anzahl,Plätze 3),Anzahl,Plätze 3),Anzahl,...,Plätze 3),Anzahl,Plätze 3),Anzahl,Plätze 3),Anzahl,Plätze 3),Insgesamt 2),Je Wohnheimplatz,NaN
7,Hochschulort/Land,Anzahl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Anzahl,NaN,NaN,NaN,NaN
8,Aalen,3,251,3,251,3,251,3,251,4,...,421,6,421,6,421,7,531,4117,8,11
9,Albstadt,-,20,-,20,-,20,2,80,-,...,82,2,82,2,82,2,82,1392,17,18
10,Bad Mergentheim 4),-,-,-,-,-,-,-,-,-,...,35,2,35,2,35,2,35,550,16,15
11,Biberach,1,63,1,63,1,63,1,63,1,...,64,1,64,1,64,1,64,2122,33,34
12,Esslingen 5),3,382,3,382,3,393,3,393,3,...,857,6,857,6,857,5,857,4807,6,5
13,Freiburg,18,3917,18,3926,20,4040,18,4066,6,...,5914,54,6266,56,6524,57,6649,32523,5,5
14,Friedrichshafen,-,-,-,-,-,-,-,-,-,...,198,1,198,1,197,1,197,1708,9,8

In [6]:
mask = df_raw.apply(lambda row: row.astype(str).str.contains("Hochschulort", na=False).any(), axis=1)
row_idx = df_raw.index[mask][0]
row_idx

2

In [7]:
df = pd.read_excel(path_xlsx, sheet_name=sheet, header=[row_idx, row_idx+1, row_idx+2])
df.shape

C:\Users\User\anaconda3\lib\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

(251, 54)

In [8]:
df.columns[:8], df.head(5)

(MultiIndex([('Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1)', ...),
             ('Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1)', ...),
             ('Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1)', ...),
             ('Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1)', ...),
             ('Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1)', ...),
             ('Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1)', ...),
             ('Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1)', ...),
             ('Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1)', ...)],
            ),
   Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1)  \
                                                                                        Unnamed: 0_level_1
                                                                                        Unnamed: 0_level_2
 0                                                NaN
 1                                                NaN
 2                                  Hochschulort/Land
 3                                              Aalen
 4                                           Albstadt

                                                                      \
      Unnamed: 1_level_1    Unnamed: 2_level_1    Unnamed: 3_level_1
   Studierendenwohnheime Studierendenwohnheime Studierendenwohnheime
 0                  2001                   NaN                  2002
 1                Anzahl             Plätze 3)                Anzahl
 2                Anzahl                   NaN                   NaN
 3                     3                   251                     3
 4                     -                    20                     -

                                                                      \
      Unnamed: 4_level_1    Unnamed: 5_level_1    Unnamed: 6_level_1
   Studierendenwohnheime Studierendenwohnheime Studierendenwohnheime
 0                   NaN                  2003                   NaN
 1             Plätze 3)                Anzahl             Plätze 3)
 2                   NaN                   NaN                   NaN
 3                   251                     3                   251
 4                    20                     -                    20

                                                                      ...  \
      Unnamed: 7_level_1    Unnamed: 8_level_1    Unnamed: 9_level_1  ...
   Studierendenwohnheime Studierendenwohnheime Studierendenwohnheime  ...
 0                  2004                   NaN                  2005  ...
 1                Anzahl             Plätze 3)                Anzahl  ...
 2                   NaN                   NaN                   NaN  ...
 3                     3                   251                     4  ...
 4                     2                    80                     -  ...

                                                                      \
     Unnamed: 44_level_1   Unnamed: 45_level_1   Unnamed: 46_level_1
   Studierendenwohnheime Studierendenwohnheime Studierendenwohnheime
 0                   NaN                  2023                   NaN
 1             Plätze 3)                Anzahl             Plätze 3)
 2                   NaN                   NaN                   NaN
 3                   421                     6                   421
 4                    82                     2                    82

                                                                       \
     Unnamed: 47_level_1   Unnamed: 48_level_1    Unnamed: 49_level_1
   Studierendenwohnheime Studierendenwohnheime Studierenden-wohnheime
 0                  2024                   NaN                   2025
 1                Anzahl             Plätze 3)                 Anzahl
 2                   NaN                   NaN                 Anzahl
 3                     6                   421                      7
 4                     2                    82                      2

                                                                   \
      Unnamed: 50_level_1 Unnamed: 51_level_1 Unnamed: 52_level_1
   Studierenden-wohnheime        Studierende         Studierende
 0                    NaN        WS 2024/2025                2025
 1              Plätze 3)        Insgesamt 2)    Je Wohnheimplatz
 2                    NaN                 NaN                 NaN
 3                    531                4117                   8
 4                     82                1392                  17


   Unnamed: 53_level_1
          Studierende
 0                2024
 1                 NaN
 2                 NaN
 3                  11
 4                  18

 [5 rows x 54 columns])

In [9]:
sheet = xls.sheet_names[0]

df = pd.read_excel(
    path_xlsx,
    sheet_name=sheet,
    header=[row_idx, row_idx + 1, row_idx + 2]
)

df.shape, df.columns.nlevels

C:\Users\User\anaconda3\lib\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

((251, 54), 3)

In [10]:
df.iloc[:5, :3]

  Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1)  \
                                                                                       Unnamed: 0_level_1
                                                                                       Unnamed: 0_level_2
0                                                NaN
1                                                NaN
2                                  Hochschulort/Land
3                                              Aalen
4                                           Albstadt


     Unnamed: 1_level_1    Unnamed: 2_level_1
  Studierendenwohnheime Studierendenwohnheime
0                  2001                   NaN
1                Anzahl             Plätze 3)
2                Anzahl                   NaN
3                     3                   251
4                     -                    20

In [11]:
df_flat = df.copy()
df_flat.columns = [
    " | ".join([str(x).strip() for x in col]).replace("nan", "").strip(" | ")
    for col in df_flat.columns
]

df_flat.columns[:15]

Index(['Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 0_level_1 | Unnamed: 0_level_2',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 1_level_1 | Studierendenwohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 2_level_1 | Studierendenwohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 3_level_1 | Studierendenwohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 4_level_1 | Studierendenwohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 5_level_1 | Studierendenwohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 6_level_1 | Studierendenwohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 7_level_1 | Studierendenwohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 8_level_1 | Studierendenwohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 9_level_1 | Studierendenwohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 10_level_1 | Studierendenwohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 11_level_1 | Studierendenwohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 12_level_1 | Studierendenwohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 13_level_1 | Studierendenwohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 14_level_1 | Studierendenwohnheime'],
      dtype='object')

In [12]:
first_col = df_flat.columns[0]
first_col

'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 0_level_1 | Unnamed: 0_level_2'

In [13]:
df_flat = df_flat.rename(columns={first_col: "hochschulort"})
df_flat[["hochschulort"]].head(10)

         hochschulort
0                 NaN
1                 NaN
2   Hochschulort/Land
3               Aalen
4            Albstadt
5  Bad Mergentheim 4)
6            Biberach
7        Esslingen 5)
8            Freiburg
9     Friedrichshafen

In [14]:
cols_interest = [c for c in df_flat.columns if ("WS 2024/2025" in c) or ("2025" in c)]
cols_interest

[]

In [15]:
preview_cols = ["hochschulort"] + cols_interest
df_flat[preview_cols].head(10)

         hochschulort
0                 NaN
1                 NaN
2   Hochschulort/Land
3               Aalen
4            Albstadt
5  Bad Mergentheim 4)
6            Biberach
7        Esslingen 5)
8            Freiburg
9     Friedrichshafen

In [16]:
start_idx = df_flat.index[df_flat["hochschulort"].astype(str).str.contains("Hochschulort/Land", na=False)][0]
start_idx

2

In [17]:
df_data = df_flat.loc[start_idx:].copy()
df_data.head(5)

,hochschulort,"Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 1_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 2_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 3_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 4_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 5_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 6_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 7_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 8_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 9_level_1 | Studierendenwohnheime",...,"Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 44_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 45_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 46_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 47_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 48_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 49_level_1 | Studierenden-wohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 50_level_1 | Studierenden-wohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 51_level_1 | Studierende","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 52_level_1 | Studierende","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 53_level_1 | Studierende"
2,Hochschulort/Land,Anzahl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Anzahl,NaN,NaN,NaN,NaN
3,Aalen,3,251,3,251,3,251,3,251,4,...,421,6,421,6,421,7,531,4117,8,11
4,Albstadt,-,20,-,20,-,20,2,80,-,...,82,2,82,2,82,2,82,1392,17,18
5,Bad Mergentheim 4),-,-,-,-,-,-,-,-,-,...,35,2,35,2,35,2,35,550,16,15
6,Biberach,1,63,1,63,1,63,1,63,1,...,64,1,64,1,64,1,64,2122,33,34

In [18]:
df_data = df_data[df_data["hochschulort"] != "Hochschulort/Land"].copy()
df_data[["hochschulort"]].head(10)

          hochschulort
3                Aalen
4             Albstadt
5   Bad Mergentheim 4)
6             Biberach
7         Esslingen 5)
8             Freiburg
9      Friedrichshafen
10          Furtwangen
11          Geislingen
12        Göppingen 5)

In [19]:
cols_interest = [c for c in df_data.columns if ("2025" in c) or ("WS 2024/2025" in c)]
len(cols_interest), cols_interest[:20]

(0, [])

In [20]:
df_data[["hochschulort"] + cols_interest[:8]].head(10)

          hochschulort
3                Aalen
4             Albstadt
5   Bad Mergentheim 4)
6             Biberach
7         Esslingen 5)
8             Freiburg
9      Friedrichshafen
10          Furtwangen
11          Geislingen
12        Göppingen 5)

In [21]:
df_data.columns[-15:]

Index(['Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 39_level_1 | Studierendenwohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 40_level_1 | Studierendenwohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 41_level_1 | Studierendenwohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 42_level_1 | Studierendenwohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 43_level_1 | Studierendenwohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 44_level_1 | Studierendenwohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 45_level_1 | Studierendenwohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 46_level_1 | Studierendenwohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 47_level_1 | Studierendenwohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 48_level_1 | Studierendenwohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 49_level_1 | Studierenden-wohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 50_level_1 | Studierenden-wohnheime',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 51_level_1 | Studierende',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 52_level_1 | Studierende',
       'Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 53_level_1 | Studierende'],
      dtype='object')

In [22]:
df_data.iloc[:10, -15:]

,"Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 39_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 40_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 41_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 42_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 43_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 44_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 45_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 46_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 47_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 48_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 49_level_1 | Studierenden-wohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 50_level_1 | Studierenden-wohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 51_level_1 | Studierende","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 52_level_1 | Studierende","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 53_level_1 | Studierende"
3,6,421,6,421,6,421,6,421,6,421,7,531,4117,8,11
4,2,92,2,82,2,82,2,82,2,82,2,82,1392,17,18
5,2,35,2,35,2,35,2,35,2,35,2,35,550,16,15
6,1,64,1,64,1,64,1,64,1,64,1,64,2122,33,34
7,5,857,5,857,5,857,6,857,6,857,5,857,4807,6,5
8,55,5264,49,5517,51,5914,54,6266,56,6524,57,6649,32523,5,5
9,1,198,1,198,1,198,1,198,1,197,1,197,1708,9,8
10,6,376,6,380,5,302,5,296,5,289,5,291,2458,8,9
11,4,245,4,244,4,244,4,244,4,244,4,244,3020,12,9
12,1,158,1,158,1,158,1,158,1,128,1,128,1040,8,9

In [23]:
df_data[df_data["hochschulort"].astype(str).str.contains("Wuppertal", na=False)].iloc[:, -15:]

,"Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 39_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 40_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 41_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 42_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 43_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 44_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 45_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 46_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 47_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 48_level_1 | Studierendenwohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 49_level_1 | Studierenden-wohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 50_level_1 | Studierenden-wohnheime","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 51_level_1 | Studierende","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 52_level_1 | Studierende","Studierendenwohnheime, Wohnheimplätze, Studierende sowie Wohnheimplatzrelationen nach Hochschulorten 1) | Unnamed: 53_level_1 | Studierende"
156,7,1217,7,1217,7,1217,7,1217,7,1217,7,1217,20883,17,18

In [24]:
# Wir nutzen die letzten Spalten per Position, weil die Header in der Datei komplex sind.
# Letzte Spalten (von hinten):
# -5: 2025 Anzahl Studierendenwohnheime
# -4: 2025 Plätze
# -3: Studierende WS 2024/2025 (Insgesamt)
# -2: Je Wohnheimplatz (Studierende pro Platz, 2025)
# -1: Studierende 2024 (lassen wir hier erstmal weg)

col_wohnheime_2025 = df_data.columns[-5]
col_plaetze_2025   = df_data.columns[-4]
col_stud_ws_2425   = df_data.columns[-3]
col_ratio_2025     = df_data.columns[-2]

df_de_obtain = df_data[[
    "hochschulort",
    col_wohnheime_2025,
    col_plaetze_2025,
    col_stud_ws_2425,
    col_ratio_2025
]].copy()

df_de_obtain = df_de_obtain.rename(columns={
    col_wohnheime_2025: "wohnheime_2025_anzahl",
    col_plaetze_2025:   "wohnheimplaetze_2025",
    col_stud_ws_2425:   "studierende_ws_2024_2025",
    col_ratio_2025:     "studierende_je_wohnheimplatz_2025"
})

df_de_obtain.head()

,hochschulort,wohnheime_2025_anzahl,wohnheimplaetze_2025,studierende_ws_2024_2025,studierende_je_wohnheimplatz_2025
3,Aalen,7,531,4117,8
4,Albstadt,2,82,1392,17
5,Bad Mergentheim 4),2,35,550,16
6,Biberach,1,64,2122,33
7,Esslingen 5),5,857,4807,6

In [25]:
df_de_obtain.shape, df_de_obtain.isna().sum()

((248, 5),
 hochschulort                          9
 wohnheime_2025_anzahl                43
 wohnheimplaetze_2025                 43
 studierende_ws_2024_2025             43
 studierende_je_wohnheimplatz_2025    43
 dtype: int64)

In [26]:
df_de_obtain[df_de_obtain["hochschulort"].astype(str).str.contains("Wuppertal", na=False)]

,hochschulort,wohnheime_2025_anzahl,wohnheimplaetze_2025,studierende_ws_2024_2025,studierende_je_wohnheimplatz_2025
156,Wuppertal,7,1217,20883,17

In [27]:
from pathlib import Path

out_path = Path("../../data/processed/student_housing_de_obtain.csv")
out_path.parent.mkdir(parents=True, exist_ok=True)

df_de_obtain.to_csv(out_path, index=False)
out_path

WindowsPath('../../data/processed/student_housing_de_obtain.csv')

In [28]:
out_path.exists()

True